sylius_return_admin:
    resource: "@SyliusReturnPlugin/config/routes/admin_routing.yaml"
    prefix: '/%sylius_admin.path_name%'

sylius_return_shop:
    resource: "@SyliusReturnPlugin/config/routes/shop_routing.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
